#!/usr/bin/env node
require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { Command } = require('commander');
const Docker = require('dockerode');
const ora = require('ora');
const chalk = require('chalk');
// NEW: Import the Google AI SDK
const { GoogleGenerativeAI } = require('@google/generative-ai');

const program = new Command();
const docker = new Docker();

// NEW: Initialize Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

function formatPathForDocker(rawPath) {
  // Fixes: "D:\GhostDock" -> "/d/GhostDock" (The universal format for Docker Toolbox/Desktop)
  // This ensures the drive letter is lowercase and properly formatted.
  let safePath = rawPath.replace(/\\/g, '/');
  
  // If it starts with a drive letter (e.g. "D:/"), convert to "/d/"
  if (/^[a-zA-Z]:\//.test(safePath)) {
    const driveLetter = safePath.charAt(0).toLowerCase();
    safePath = `/${driveLetter}${safePath.slice(2)}`;
  }
  return safePath;
}

// NEW: The "Peeking" Function
// Reads the first 1000 characters so the AI understands the file structure
function getFilePreview(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  return content.substring(0, 1000) + (content.length > 1000 ? '\n...(truncated)' : '');
}

program
  .name('airlock')
  .description('Securely modify local files using AI')
  .version('1.0.0');

program
  .command('edit')
  .argument('<file>', 'The file you want to modify')
  .option('-i, --instruction <text>', 'Instruction')
  .action(async (filePath, options) => {
    const spinner = ora('Initializing Airlock...').start();

    try {
      const absolutePath = path.resolve(filePath);
      const fileDir = path.dirname(absolutePath);
      const fileName = path.basename(absolutePath);
      const dockerSafeDir = formatPathForDocker(fileDir);

      if (!fs.existsSync(absolutePath)) {
        spinner.fail('File not found!');
        return;
      }

      // --- STEP A: CONSULT THE BRAIN ---
      spinner.text = 'Reading file preview...';
      const filePreview = getFilePreview(absolutePath);

      spinner.text = 'Consulting Gemini (Cloud)...';
      
      const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
      const prompt = `
        You are an expert Python coder.
        
        TASK:
        1. Read "/data/${fileName}".
        2. Perform instruction: "${options.instruction}".
        3. Overwrite "/data/${fileName}" with the result.
        
        CONTEXT:
        - File Content Preview:
        """
        ${filePreview}
        """

        CRITICAL REQUIREMENTS:
        1. You MUST print "DEBUG: Reading file..." before opening.
        2. You MUST print "DEBUG: Row count: [number]" after reading.
        3. You MUST print "DEBUG: Writing file..." before writing.
        4. You MUST print "SUCCESS" only if no errors occur.
        5. Wrap ALL file operations in a try/except block and print the error message if it fails.
        6. Return ONLY executable Python code.
      `;

      const result = await model.generateContent(prompt);
      const response = await result.response;
      let aiCode = response.text();

      // CLEANUP: Remove markdown backticks if Gemini adds them
      aiCode = aiCode.replace(/```python/g, '').replace(/```/g, '').trim();

      spinner.succeed('Plan generated by AI.');
      console.log(chalk.gray(aiCode)); // Uncomment to see the generated code

      // --- STEP B: EXECUTE WITH HANDS ---
      spinner.start('Spinning up OFFLINE container...');

      const container = await docker.createContainer({
        Image: 'python:3.11-slim',
        Cmd: ['python', '-c', aiCode], // <--- We inject the REAL AI code now
        NetworkDisabled: true,
        HostConfig: {
          Binds: [`${dockerSafeDir}:/data`]
        }
      });

      await container.start();
      await container.wait(); 
      
      const logs = await container.logs({ stdout: true, stderr: true });
      await container.remove();

      spinner.stop();
      console.log(chalk.blue('\n--- Container Logs ---'));
      console.log(logs.toString('utf-8'));
      
      console.log(chalk.green('\nProcess Complete. Check your file!'));

    } catch (error) {
      spinner.fail('Mission Failed');
      console.error(chalk.red(error.message));
    }
  });

program.parse();